### ISSUE TITLE
Déploiement environnement de tests

### ISSUE THREAD

**Issue by dofbi** [AfricTivistes/CartoCivicElections#5]
Déploiement environnement de tests

**Comment by dofbi** [comment]
Salaam @mbayedione10 
Tu peux déployer la **branche initiatives** dans un envirnonement de tests et partager le lien 
Merci 🙏🏾

**Comment by mbayedione10** [comment]
Salam @dofbi 
je viens de deployer la partie test dans le meme netlify que la prod
https://app.netlify.com/sites/cisca/overview
Voici le preview https://cisca.netlify.app/
